[project]
name = "grpo-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch-c-dlpack-ext>=0.1.3",
    "unsloth>=2025.11.3",
    "vllm>=0.11.2",
]
